title: Ed Britton
description: 
google_analytics: 
show_downloads: false
lang: en_GB

author:
  name: Ed Britton
  twitter: edbritton

twitter:
  username: edbritton
  card: summary

social:
  name: Ed Britton
  links:
    - https://twitter.com/edbritton
    - https://youtube.com/edbritton
    - https://imdb.com/name/nm10740536

permalink: /:categories/:short_year:y_day/

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-mentions
  - jekyll-seo-tag
  # - jekyll-coffeescript
  - jekyll-redirect-from

jekyll-mentions: https://twitter.com

defaults:
  -
    scope:
      path: "themes" # an empty string here means all files in the project
      type: "pages"
    values:
      producer: The Internet
      title: E<span class="blink">d</span> <span class="blink">Br</span>it<span class="blink">t</span>on
      imdb: https://imdb.com/name/nm10740536
      image: default.jpg
      genre: MICF
      greentext: 92% British
      duration: 1m&nbsp;80cm
      classification: MA 15+
  - scope:
      path: "/"
      type: "pages"
    values:
      layout: apostrophe
      image: default.jpg
      embed:
        src: https://www.youtube.com/embed/videoseries?list=PLvO7_P5xOL8VK0G9HfZ8OL2oVdIh0gkT3
        caption: My latest vlog.
        cite: 'https://youtube.com/edbritton'
  - scope:
      path: "404.md"
    values:
      embed: false
