title: Ed Britton
description: 
google_analytics: 
show_downloads: false
lang: en_GB

author:
  name: Ed Britton
  twitter: edbritton

twitter:
  username: edbritton
  card: summary

social:
  name: Ed Britton
  links:
    - https://twitter.com/edbritton
    - https://imdb.com/name/nm10740536

permalink: /:categories/:short_year:y_day/

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-mentions
  - jekyll-seo-tag

jekyll-mentions: https://twitter.com

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      producer: The Internet
      title: E<span class="blink">d</span> <span class="blink">Br</span>it<span class="blink">t</span>on
      imdb: https://imdb.com/name/nm10740536
      image: default.jpg
      genre: MICF
      greentext: 92% British
      duration: 1m&nbsp;80cm
      classification: MA 15+
