title: Ed Britton
description: 
google_analytics: 
show_downloads: true
#theme: jekyll-theme-minimal

permalink: /:categories/:year:month:day:hour:minute/

plugins:
  - jekyll-mentions

jekyll-mentions: https://twitter.com
