title: Ed Britton
description: 
google_analytics: 
show_downloads: true
#theme: jekyll-theme-minimal

permalink: /:categories/:short_year:y_day/

plugins:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-autolink_email

jekyll-mentions: https://twitter.com
