title: Ed Britton
description: 
google_analytics: 
show_downloads: false
lang: en_GB

author:
  name: Ed Britton
  twitter: edbritton

twitter:
  username: edbritton
  card: summary

social:
  name: Ed Britton
  links:
    - https://twitter.com/edbritton
    - https://imdb.com/name/nm10740536

permalink: /:categories/:short_year:y_day/

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-mentions
  - jekyll-seo-tag

jekyll-mentions: https://twitter.com
