title: Ed Britton
description: 
google_analytics: 
show_downloads: true
lang: en_GB
author:
  twitter: edbritton
twitter:
  username: edbritton
  card: summary
social:
  name: Ed Britton
  links:
    - https://twitter.com/edbritton
    - https://imdb.com/name/nm10740536

permalink: /:categories/:short_year:y_day/

plugins:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-autolink_email
  - jekyll-ical-tag

jekyll-mentions: https://twitter.com
