title: Ed Britton
description: 
google_analytics: 
show_downloads: true
#theme: jekyll-theme-minimal

permalink: /blog/:year:month:day/

plugins:
  - jekyll-mentions

jekyll-mentions: https://twitter.com
